Create Header and MainContainer components for layout
stobar93/dooper-bootcamp pull request #3
Opened 2022-04-08 10:30 UTC by stobar93

Se crearon los componentes Header y MainContainer para componer el layout.

2022-04-08 15:12 UTC, ferpintado requested changes

2022-04-08 15:12 UTC, ferpintado commented on package.json
> +    "styled-components": "^5.3.5"
`@mui` ya tiene styled components https://mui.com/system/styled/

2022-04-08 15:12 UTC, ferpintado commented on src/components/Header/Header.tsx
> +type HeaderProps = {};
Si no hay propiedades, es recomendable borrar este type para evitar contaminacion en el codigo

2022-04-08 15:12 UTC, ferpintado commented on src/components/Header/NavBar/NavBar.tsx
> +type NavBarProps = {};
Si no se necesita, es recomendable removerlo

2022-04-08 15:12 UTC, ferpintado commented on src/components/Header/NavBar/NavBar.tsx
> +type page = {
Como buena practica se recomienda declarar types seguido de `Props` por ejemplo `PageProps`

2022-04-08 16:43 UTC, JustinoTorreblanca approved these changes
Me gustó como separaste  en varios componentes el Header, no había considerado hacerlo de esa manera.

2022-04-08 18:07 UTC, ferpintado commented on src/components/Header/NavBar/NavBar.tsx
> +import Link from "next/link";
al ser un componente "hijo" de Header, seria ideal colocarlo dentro de `Header/components` tal cual el generador `yarn generate component` sugiere para asi todos seguir la misma estructura

2022-04-12 16:06 UTC, ferpintado approved these changes

2022-04-12 16:10 UTC, merged