Sebastian/boo 25 1 create register component
stobar93/dooper-bootcamp pull request #4
Opened 2022-04-15 05:50 UTC by stobar93

https://linear.app/dooper/issue/BOO-25/1-create-register-component

![image](https://user-images.githubusercontent.com/86356868/163527126-0e891dbb-7219-4fd0-9dd6-a2e5a60cdd50.png)

![image](https://user-images.githubusercontent.com/86356868/163527074-0706cccc-2ce2-4abc-896f-35e16cf0d8ba.png)

2022-04-15 16:39 UTC, ferpintado requested changes

2022-04-15 16:39 UTC, ferpintado commented on src/hooks/useFormConfig/useFormConfig.tsx
> +  id: "firstName" | "lastName" | "email" | "password" | "phone_number";
yo lo dejaria como `string` porque asi estas limitando a solamente esos campos y no seria tan reusable

2022-04-15 16:39 UTC, ferpintado commented on src/hooks/useFormConfig/useFormConfig.tsx
> +const validationDictionary = {
para hacerlo un poco reusable yo recomendaria que fuera en tipo de campo por ejemplo `string` o `password` o `email` y en base a hacer tener el dictionary que jalara el tipo de validacion que se tiene que hacer

2022-04-15 17:45 UTC, stobar93 commented on src/hooks/useFormConfig/useFormConfig.tsx
> +const validationDictionary = {
De acuerdo. Ya quedo corregido
Gracias

2022-04-15 17:46 UTC, stobar93 commented on src/hooks/useFormConfig/useFormConfig.tsx
> +  id: "firstName" | "lastName" | "email" | "password" | "phone_number";
Listo, Lo deje como string, sin embargo tuve que crear un type FieldTypes para usarlo en la validacion, sino no me deja indexar el diccionario

2022-04-18 14:51 UTC, JustinoTorreblanca approved these changes
Buen trabajo, me agrada el feedback que le das al usuario, cuando deja el formulario vacío y hace click fuera de este.

2022-04-18 15:21 UTC, ferpintado approved these changes

2022-04-19 00:36 UTC, merged