Sebastian/boo 27 3 create profile component
stobar93/dooper-bootcamp pull request #6
Opened 2022-04-16 02:27 UTC by stobar93

https://linear.app/dooper/issue/BOO-27/3-create-profile-component

![image](https://user-images.githubusercontent.com/86356868/163658027-8a40fc4a-1d51-4872-a522-13069afc6e39.png)

2022-04-18 14:06 UTC, JustinoTorreblanca approved these changes
Buen trabajo Sebastian, solo una observación... En el Login component el botón inicialmente le puedes hacer click y enviar el formulario vacío, pero si pongo algún password el botón se vuelve "disabled".

2022-04-20 00:52 UTC, ferpintado requested changes

2022-04-20 00:52 UTC, ferpintado commented on src/components/Profile/styles.tsx
> +import { styled } from "@mui/material";
Estos archivos son opciones, si no se requiere recomiendo borrarlos.

2022-04-20 00:52 UTC, ferpintado commented on src/components/Profile/components/EditProfileForm/styles.tsx
> +export const Container = styled(Box)`
Estos estilos estan disponibles directamente en el componente `<Box display="flex" flexDirection....>` . El criterio para extender un componente como styled component es que las propiedades disponibles no sean suficientes para lo que queremos hacer

2022-04-20 00:52 UTC, ferpintado commented on src/components/Profile/components/EditProfileForm/styles.tsx
> +  @media screen and (max-width: 640px) {
recomiendo usar:
```
${theme.breakpoints.down('md')} {
   
 }
  ```
  
tambien `.up` esta disponible. Asi las medidas responsivas del theme se respetan. 

https://mui.com/material-ui/customization/breakpoints/

2022-04-21 03:32 UTC, stobar93 commented on src/components/Profile/components/EditProfileForm/styles.tsx
> +export const Container = styled(Box)`
Listo, quedo corregido. Gracias

2022-04-21 03:32 UTC, stobar93 commented on src/components/Profile/components/EditProfileForm/styles.tsx
> +  @media screen and (max-width: 640px) {
Gracias! Super practico

2022-04-21 18:04 UTC, ferpintado commented on src/components/Profile/components/EditProfileForm/styles.tsx
> +  ${({ theme }) => {
muy bien, alternativamente se hubiera podido reducir un poco mas el codigo regresando el `css` directamente
```
${({ theme }) => css`
....
`}}
```

2022-04-21 18:05 UTC, ferpintado approved these changes

2022-04-21 20:21 UTC, merged