2.2 CRUD Products UI
stobar93/dooper-bootcamp pull request #9
Opened 2022-05-02 20:57 UTC by stobar93

https://linear.app/dooper/issue/BOO-34/22-crud-products-ui

Admin/productos
![image](https://user-images.githubusercontent.com/86356868/166326322-7dc2607c-9d8e-47e8-8573-0dcf6afd3e48.png)

Editar/Crear producto
![image](https://user-images.githubusercontent.com/86356868/166326409-0a1ef885-dfe3-415e-89fb-21ad5b22e076.png)

Eliminar producto
![image](https://user-images.githubusercontent.com/86356868/166326477-d6bb7eda-4fb6-4bdd-b649-e2470c160d31.png)

2022-05-03 00:11 UTC, JustinoTorreblanca requested changes

2022-05-03 00:11 UTC, JustinoTorreblanca commented on src/components/Login/Login.tsx
> +        message: "Welcome!"
Se ve super bien, solo una sugerencia: si vas a usar castellano para el usuario considero que tendría que ser en toda la App, para no mezclar idiomas.

2022-05-03 00:11 UTC, JustinoTorreblanca commented on pages/admin/productos.tsx
> +          Aun no tienes ningun producto. Crea el primero ahora
Se ve super bien, solo una sugerencia: si vas a usar castellano para el usuario considero que tendría que ser en toda la App, para no mezclar idiomas.

2022-05-04 16:04 UTC, ferpintado commented on src/components/InputComponent/components/BooleanInput/index.ts
> +export { default } from "./SwitchInput";
Me confundio un poco el nombre del componente vs el nombre del folder, crees que seria buena idea dejarlo igual?

2022-05-04 16:08 UTC, ferpintado approved these changes

2022-05-04 18:50 UTC, stobar93 commented on src/components/InputComponent/components/BooleanInput/index.ts
> +export { default } from "./SwitchInput";
Tienes razon, gracias!

2022-05-04 19:52 UTC, ferpintado approved these changes

2022-05-05 03:45 UTC, gmz2091 approved these changes

2022-05-07 16:56 UTC, merged